version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/zoo/ # 인스턴스에서 파일이 저장될 위치
permissions: #권한 허용
  - object: /home/ubuntu/zoo/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
